version: "3"
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./app
        target: /usr/src/app
    ports:
      - 3000:3000
    stdin_open: true
